version: '3.8'

services:
  migpt:
    image: idootop/mi-gpt:latest
    container_name: kids-ai-speaker
    restart: unless-stopped
    env_file:
      - ./config/.env
    volumes:
      - ./config/.migpt.js:/app/.migpt.js:ro
      - ./logs:/app/logs